import { Camera, Cable, Crosshair, Layers3, Route, ScanLine, LayoutTemplate, ShieldCheck, ScanEye, History, FileSearch, Settings, ListChecks, type LucideIcon } from "lucide-react";
import type { View } from "./model";
export const screens: { id: View; label: string; description: string; icon: LucideIcon; group: string }[] = [
  { id: "guide", label: "操作流程", description: "从建站到复盘，一条完整的操作路径", icon: ListChecks, group: "guide" },
  { id: "live", label: "在线检测", description: "先看整件结论，再定位到拍照点、设备视角与原图", icon: ScanEye, group: "production" },
  { id: "history", label: "历史记录", description: "筛选工件、回放原始结果与图像", icon: History, group: "production" },
  { id: "record", label: "历史复测", description: "以 cycleId 追溯，区分原发布包重现与候选复测", icon: FileSearch, group: "production" },
  { id: "recipes", label: "配方库", description: "生产配方与候选版本分别管理", icon: Layers3, group: "recipe" },
  { id: "geometry", label: "拍照点规划", description: "逐点选择 Pose、设备、视角与像素中线", icon: Route, group: "recipe" },
  { id: "teach", label: "逐点示教", description: "冻结原图 → 像素中线与比例 → 试测保存", icon: ScanLine, group: "recipe" },
  { id: "overview", label: "工件总览", description: "布置显示框，点击总览定位到帧", icon: LayoutTemplate, group: "recipe" },
  { id: "validation", label: "验证与发布", description: "验证候选配置，在安全时点切换版本", icon: ShieldCheck, group: "recipe" },
  { id: "device", label: "设备与采集", description: "核对相机身份与采集参数", icon: Camera, group: "setup" },
  { id: "plc", label: "PLC 通讯", description: "确认连接、点位和业务握手", icon: Cable, group: "setup" },
  { id: "calibration", label: "飞拍工位标定", description: "检查标定质量，保存毫米换算版本", icon: Crosshair, group: "setup" },
  { id: "settings", label: "系统设置", description: "管理时序、图像留存与运行诊断", icon: Settings, group: "setup" },
];
export const scenes: { id: string; label: string; view: View; group: string }[] = [
  ["device-setup", "设备与采集", "device", "建站"],
  ["plc-setup", "PLC 握手", "plc", "建站"],
  ["calibration", "标定成功", "calibration", "建站"],
  ["recipe-library", "配方库", "recipes", "配方"],
  ["recipe-geometry", "逐点规划完整", "geometry", "配方"],
  ["teach-raw", "冻结图像", "teach", "示教"],
  ["overview-setup", "总览布置", "overview", "配方"],
  ["validation-release", "待批量验证", "validation", "验证"],
  ["live-wait", "等待工件", "live", "生产"],
  ["history-list", "历史筛选", "history", "历史"],
  ["history-detail", "原始记录", "record", "历史"],
  ["system-settings", "系统设置", "settings", "建站"],
  ["teach-empty", "尚未取样", "teach", "示教"],
  ["teach-pass", "试测通过", "teach", "示教"],
  ["teach-fail", "试测失败", "teach", "示教"],
  ["teach-saved", "本点已保存", "teach", "示教"],
  ["teach-stale", "参数变更待重采", "teach", "示教"],
  ["teach-k4", "选中 k4", "teach", "示教"],
  ["teach-history", "历史样本示教", "teach", "示教"],
  ["three-view", "单设备三目选视角", "geometry", "配方"],
  ["coverage-fail", "像素中线超出原图", "geometry", "异常"],
  ["calibration-fail", "未识别标定角点", "calibration", "异常"],
  ["validation-blocked", "发布条件未满足", "validation", "验证"],
  ["validation-pass", "验证通过", "validation", "验证"],
  ["validation-released", "生产版本已更新", "validation", "验证"],
  ["live-running", "工件采集中", "live", "生产"],
  ["live-ng", "断胶 NG", "live", "生产"],
  ["live-err", "测量异常 ERR", "live", "生产"],
  ["live-k4", "整件 NG · 查看 k4", "live", "生产"],
  ["history-no-raw", "原图已清理", "record", "历史"],
  ["history-compare", "原始与候选对照", "record", "历史"],
  ["publish-confirm", "发布确认", "validation", "验证"],
].map(([id, label, view, group]) => ({ id, label, view: view as View, group }));
export const journeys: { title: string; detail: string; views: View[] }[] = [
  { title: "首次建站", detail: "设备、握手、标定、示教、验证，依次完成。", views: ["device", "plc", "calibration", "recipes", "geometry", "teach", "overview", "validation", "live"] },
  { title: "日常生产", detail: "启动检测，定位异常，回放原始记录。", views: ["live", "history", "record"] },
  { title: "缺陷排查", detail: "从缺陷点取历史样本，修改像素中线并试测后重新验证。", views: ["live", "record", "teach", "validation", "live"] },
  { title: "配置变更", detail: "修改候选配置，验证后更新生产版本。", views: ["recipes", "geometry", "teach", "overview", "validation", "live"] },
];
export const routeTo = (view: View) => "/workflow/" + view;
