import { useState } from "react";
import { Camera, Check, ChevronRight, Link2, Power, Save, Unplug, WandSparkles } from "lucide-react";
import { useWorkflow } from "./context";
import { plcPoints } from "./model";
import { Badge, BusyLabel, FrameCanvas, KV, Notice, NumberField, Panel, SelectField, useTask } from "./components";

export function DeviceView() {
  const { state: s, dispatch, go, notify } = useWorkflow();
  const [sampleDevice, setSampleDevice] = useState<typeof s.device | null>(null);
  const captured = sampleDevice === s.device && s.device.connected && s.device.applied;
  const locked = s.live.phase > 0 && s.live.phase < 4;
  const valid = s.device.exposure >= 10 && s.device.exposure <= 10000 && s.device.gain >= 0 && s.device.gain <= 24;
  const task = useTask();
  return <>
    {task.error && <Notice title="预览操作失败" tone="warn">{task.error}</Notice>}
    <div className="wf-page-actions"><Badge tone={s.device.connected ? "ok" : "warn"}>{s.device.connected ? "相机已连接" : "相机未连接"}</Badge><div className="wf-row"><button className="btn" disabled={locked || task.busy} onClick={() => dispatch({ type: "device", patch: { connected: !s.device.connected, applied: false } })}>{s.device.connected ? <Unplug size={15} /> : <Link2 size={15} />}{s.device.connected ? "断开" : "连接相机"}</button><button className="btn primary" onClick={() => go("plc")}>下一步 · PLC 通讯<ChevronRight size={15} /></button></div></div>
    {locked && <Notice title="当前工件正在采集，采集参数暂时锁定" tone="warn">完成本件后再应用新参数，避免同一工件混用采集条件。</Notice>}
    <div className="wf-two-col">
      <div className="stack"><Panel title="相机身份" detail="确认工位与设备的固定对应关系"><div className="wf-device-card"><Camera size={30} /><div><strong>相机 1 · 飞拍工位</strong><p className="wf-caption">GigE Area Scan · SN-0001</p></div><Badge tone={s.device.connected ? "ok" : "warn"}>{s.device.connected ? "在线" : "离线"}</Badge></div><KV label="设备地址">192.168.1.21</KV><KV label="图像大小">2448 × 2048 px</KV><KV label="采集方式">外部硬件触发</KV><KV label="业务状态">{s.device.applied && s.device.connected ? <span className="ok">已就绪</span> : <span className="wf-warn-text">待应用参数</span>}</KV></Panel>
      <Panel title="采集参数" detail="参数写入后核对设备接受的值"><div className="wf-form-grid"><NumberField label="曝光时间" value={s.device.exposure} min={10} max={10000} unit="μs" disabled={locked || task.busy} onChange={v => dispatch({ type: "device", patch: { exposure: v } })} /><NumberField label="增益" value={s.device.gain} max={24} step={0.1} unit="dB" disabled={locked || task.busy} onChange={v => dispatch({ type: "device", patch: { gain: v } })} /><SelectField label="触发源" value={s.device.trigger} options={["Line0 · 上升沿", "Line1 · 上升沿", "软件触发"]} disabled={locked || task.busy} onChange={v => dispatch({ type: "device", patch: { trigger: v } })} /><label className="wf-field"><span>读回曝光</span><div className="wf-readout">{s.device.applied ? s.device.exposure + " μs" : "等待参数接受"}</div></label></div><div className="wf-actions"><button className="btn primary" disabled={!s.device.connected || !valid || locked || task.busy} onClick={() => task.run(() => { dispatch({ type: "device", patch: { applied: true } }); notify("采集参数已接受，请重新取样验证。"); })}><BusyLabel busy={task.busy}><Save size={15} />保存并应用参数</BusyLabel></button>{s.device.applied && <span className="wf-caption ok"><Check size={13} /> 参数已接受</span>}</div></Panel></div>
      <Panel title="采集预览" detail="取帧仅用于检查图像与采集条件" actions={<button className="btn" disabled={!s.device.connected || !s.device.applied || locked || task.busy} onClick={() => setSampleDevice(s.device)}><Camera size={15} />取一帧</button>}><FrameCanvas id={3} imageId={captured ? 50 : null} label="采集预览" /><div className="wf-stat-grid"><div><span>帧时间</span><strong>{captured ? "179 ms" : "—"}</strong></div><div><span>示例触发频率</span><strong>5.6 fps</strong></div><div><span>曝光</span><strong>{s.device.applied ? s.device.exposure + " μs" : "待应用"}</strong></div></div></Panel>
    </div>
  </>;
}

export function PlcView() {
  const { state: s, dispatch, go, notify } = useWorkflow();
  const points = s.plc.points;
  const dirty = !s.plc.pointsApplied;
  const [events, setEvents] = useState<string[]>([]);
  const valid = /^(\d{1,3}\.){3}\d{1,3}$/.test(s.plc.address) && s.plc.address.split(".").every(n => Number(n) <= 255);
  const phases = ["开始信号", "相机布防", "采集结束", "结果就绪", "结果码", "PLC 确认"];
  const locked = s.live.phase > 0 && s.live.phase < 4;
  return <>
    <div className="wf-page-actions"><div className="wf-row"><Badge tone={s.plc.connected ? "ok" : "warn"}>{s.plc.connected ? "通讯已连接" : "通讯未连接"}</Badge><Badge tone={s.plc.ready ? "ok" : "warn"}>{s.plc.ready ? "业务握手就绪" : "业务握手待检查"}</Badge></div><button className="btn primary" onClick={() => go("calibration")}>下一步 · 工位标定<ChevronRight size={15} /></button></div>
    <div className="wf-two-col"><div className="stack"><Panel title="连接设置"><div className="wf-form-grid"><SelectField label="通讯协议" value={s.plc.protocol} options={["S7", "Modbus TCP"]} disabled={locked} onChange={v => { dispatch({ type: "plc", patch: { protocol: v, connected: false, ready: false, points: plcPoints(v), pointsApplied: false } }); }} /><label className="wf-field"><span>PLC 地址</span><input className="input" aria-label="PLC 地址" aria-invalid={!valid} disabled={locked} value={s.plc.address} onChange={e => dispatch({ type: "plc", patch: { address: e.target.value, connected: false, ready: false } })} /><small>{!valid ? "请输入有效的 IPv4 地址" : "示例工位 · 192.168.1.10"}</small></label></div><KV label={s.plc.protocol === "S7" ? "机架 / 插槽" : "端口 / 站号"}>{s.plc.protocol === "S7" ? "0 / 1" : "502 / 1"}</KV><div className="wf-actions"><button className="btn primary" disabled={!valid || locked} onClick={() => { dispatch({ type: "plc", patch: { connected: !s.plc.connected, ready: false } }); setEvents(["通讯连接状态已更新"]); }}>{s.plc.connected ? "断开连接" : "连接 PLC"}</button></div></Panel>
    <Panel title="业务点位" detail="点位修改后需要重新检查握手" actions={<Badge tone={dirty ? "warn" : "neutral"}>{dirty ? "有未应用修改" : "点位已应用"}</Badge>}><div className="wf-table-wrap"><table className="table wf-table"><thead><tr><th>信号</th><th>方向</th><th>地址</th></tr></thead><tbody>{phases.map((p, i) => <tr key={p}><td>{p}</td><td className="wf-caption">{[0, 2, 5].includes(i) ? "PLC → 软件" : "软件 → PLC"}</td><td><input className="input wf-point-input" aria-label={p + "地址"} value={points[i]} disabled={locked} onChange={e => { dispatch({ type: "plc", patch: { points: points.map((v, j) => j === i ? e.target.value : v), pointsApplied: false, ready: false } }); }} /></td></tr>)}</tbody></table></div><div className="wf-actions"><button className="btn" disabled={!dirty || points.some(p => !p.trim()) || locked} onClick={() => { dispatch({ type: "plc", patch: { points: points.map(p => p.trim()), pointsApplied: true } }); notify("点位已应用，请检查业务握手。"); }}>应用点位</button></div></Panel></div>
    <div className="stack"><Panel title="工件握手" detail="通讯连接和业务就绪分别确认"><ol className="wf-handshake">{["等待开始", "相机布防", "采集工件", "汇总结果", "输出结果", "收到确认"].map((p, i) => <li key={p} className={s.plc.ready ? "done" : ""}><span>{s.plc.ready ? <Check size={14} /> : i + 1}</span><div><strong>{p}</strong><small>{["PLC 发出开始信号", "相机接受本件触发", "帧计数与工件绑定", "OK / NG / ERR 分别输出", "写入结果码并保持", "清除本件状态，等待下件"][i]}</small></div></li>)}</ol><button className="btn primary" disabled={!s.plc.connected || dirty || locked} onClick={() => { dispatch({ type: "plc", patch: { ready: true } }); setEvents(["14:32:00 通讯正常", "14:32:01 业务点位检查通过", "14:32:02 握手就绪"]); notify("业务握手检查通过。"); }}><Check size={15} />检查业务握手</button></Panel><Panel title="通讯事件"><div className="wf-log">{(events.length ? events : ["14:32:00 通讯正常", "14:32:02 等待开始信号"]).map((e, i) => <div key={i}><span className="wf-log-dot" />{e}</div>)}</div><Notice title="结果码示例">0：OK　1：NG　2：ERR。异常数据独立输出，便于停机排查。</Notice></Panel></div></div>
  </>;
}

export function CalibrationView() {
  const { state: s, dispatch, go, notify } = useWorkflow();
  const task = useTask();
  const c = s.calibration;
  const locked = s.live.phase > 0 && s.live.phase < 4;
  return <>
    {task.error && <Notice title="预览操作失败" tone="warn">{task.error}</Notice>}
    {locked && <Notice title="当前工件完成后再标定" tone="warn">本件仍使用开始时的标定与采集条件。</Notice>}
    <div className="wf-page-actions"><Badge tone={c.saved ? "ok" : c.result === "fail" ? "warn" : "neutral"}>{c.saved ? "有效标定 C" + String(c.version).padStart(2, "0") : c.result === "fail" ? "标定失败" : "待保存标定"}</Badge><button className="btn primary" onClick={() => go("recipes")}>进入配方库<ChevronRight size={15} /></button></div>
    <div className="wf-two-col wf-wide-left"><Panel title="标定图像" detail="9 × 6 内角点 · 10 × 7 方格" actions={<button className="btn" disabled={!s.device.connected || task.busy || locked} onClick={() => dispatch({ type: "calibration", patch: { captured: true, result: "idle", saved: false } })}><Camera size={15} />取标定帧</button>}><div className="wf-calibration-image">{c.captured ? <svg viewBox="0 0 720 430" role="img" aria-label={c.sample === "bad" ? "未完整识别角点的棋盘格" : "9 乘 6 内角点棋盘格"}><rect width="720" height="430" fill="#151515" /><g transform="translate(110 40)">{Array.from({ length: 70 }, (_, i) => <rect key={i} x={i % 10 * 50} y={Math.floor(i / 10) * 50} width="50" height="50" fill={((i % 10) + Math.floor(i / 10)) % 2 ? "#222" : "#c2c2c2"} />)}{c.result === "pass" && Array.from({ length: 54 }, (_, i) => <g key={i} transform={"translate(" + ((i % 9 + 1) * 50) + " " + ((Math.floor(i / 9) + 1) * 50) + ")"}><circle r="5" fill="var(--accent)" /><path d="M-8 0H8M0-8V8" stroke="var(--accent-text)" /></g>)}{c.sample === "bad" && <rect x="210" width="300" height="350" fill="#151515" opacity=".94" />}</g><text x="560" y="410" fill="var(--text-muted)" fontSize="12">标定样本示意</text></svg> : <div className="wf-image-empty"><Camera size={34} /><strong>取一帧标定图像</strong><span>棋盘格需要完整进入视野</span></div>}</div><div className="wf-actions"><SelectField label="预览样本" value={c.sample === "good" ? "完整棋盘格" : "遮挡棋盘格"} options={["完整棋盘格", "遮挡棋盘格"]} disabled={task.busy || locked} onChange={v => dispatch({ type: "calibration", patch: { sample: v === "完整棋盘格" ? "good" : "bad", result: "idle", saved: false } })} /><button className="btn primary" disabled={!c.captured || task.busy || locked} onClick={() => task.run(() => dispatch({ type: "calibration", patch: { result: c.sample === "good" ? "pass" : "fail", saved: false } }))}><BusyLabel busy={task.busy}><WandSparkles size={15} />计算标定</BusyLabel></button></div></Panel>
    <div className="stack"><Panel title="标定参数"><KV label="内角点">9 × 6</KV><KV label="方格边长">10 mm</KV><KV label="使用工位">相机 1 · 飞拍</KV><KV label="换算目标">图像坐标 → 毫米</KV></Panel><Panel title="质量检查">{c.result === "pass" ? <><div className="wf-big-metric"><strong>0.08 <small>mm</small></strong><span>示例重投影误差 RMS</span></div><KV label="识别角点">54 / 54</KV><KV label="示例比例">0.040 mm / px</KV><Notice title="质量检查通过" tone="ok">保存后将更新标定版本，并要求相关帧重新示教。</Notice></> : c.result === "fail" ? <Notice title="未完整识别标定角点" tone="warn">调整棋盘格位置、曝光或对焦，重新取帧。当前结果不能保存。</Notice> : <Notice title="尚未计算当前样本">取帧后计算标定，检查角点数量与误差。</Notice>}<div className="wf-actions"><button className="btn primary" disabled={c.result !== "pass" || c.saved || task.busy || locked} onClick={() => { dispatch({ type: "calibration", patch: { saved: true } }); notify("标定已保存为 C" + String(c.version + 1).padStart(2, "0") + "，相关帧需要重新取样示教。"); }}><Save size={15} />保存标定</button></div></Panel></div></div>
  </>;
}


export function SettingsView() {
  const { state: s, dispatch, notify } = useWorkflow();
  const [tab, setTab] = useState("运行配置");
  const valid = Number.isInteger(s.settings.retention) && s.settings.retention >= 1 && s.settings.retention <= 365 && Number.isInteger(s.settings.timeout) && s.settings.timeout >= 100 && s.settings.timeout <= 60000;
  const edit = (patch: Partial<typeof s.settings>) => dispatch({ type: "settings", patch: { ...patch, saved: false } });
  return <>
    <div className="wf-page-actions"><div className="wf-tabs">{["运行配置", "诊断信息"].map(t => <button key={t} onClick={() => setTab(t)} className={tab === t ? "active" : ""}>{t}</button>)}</div><button className="btn primary" disabled={s.settings.saved || !valid} onClick={() => { dispatch({ type: "settings", patch: { saved: true } }); notify("本地预览设置已保存。"); }}><Save size={15} />保存设置</button></div>
    {tab === "运行配置" ? <div className="wf-two-col"><div className="stack"><Panel title="运行时序" detail="超时需要覆盖最长工件节拍"><NumberField label="等待工件完成超时" value={s.settings.timeout} min={100} max={60000} unit="ms" onChange={v => edit({ timeout: v })} /><KV label="示例 PLC 确认超时">1000 ms</KV><KV label="异常处理">输出 ERR，保留本件事件</KV></Panel><Panel title="图像与记录留存"><div className="wf-form-grid"><NumberField label="原图保留天数" value={s.settings.retention} min={1} max={365} unit="天" onChange={v => edit({ retention: v })} /><SelectField label="原图保存策略" value={s.settings.raw} options={["全部工件", "NG 与 ERR", "仅 ERR"]} onChange={v => edit({ raw: v })} /></div><KV label="示例历史容量">10,000 件</KV><Notice title="记录和原图分别保留">原图清理后可回放测量数据、重新判定；原图复测和示教取样将不可用。</Notice></Panel></div><div className="stack"><Panel title="存储状态" detail="预览容量示例"><div className="wf-big-metric"><strong>18.6 <small>/ 100 GB</small></strong><span>已使用</span></div><div className="wf-storage"><span /></div><KV label="预计保留范围">最近 {s.settings.retention} 天</KV><KV label="当前策略">{s.settings.raw}</KV></Panel><Panel title="运行能力"><KV label="当前运行环境"><Badge>操作流程预览</Badge></KV><KV label="相机与 PLC">示例状态</KV><KV label="图像、标定与测量">示例图像与结果</KV><KV label="原软件连接"><a href="#/inspect" className="wf-link">返回现有软件</a></KV></Panel></div></div> : <Panel title="诊断信息" detail="查看连接和配置状态"><div className="wf-stat-grid"><div><span>相机参数</span><strong>{s.device.applied ? "已接受" : "待应用"}</strong></div><div><span>PLC 业务握手</span><strong>{s.plc.ready ? "就绪" : "未就绪"}</strong></div><div><span>当前生产版本</span><strong>v{s.recipe.production}</strong></div></div><div className="wf-log">{["14:32:00 操作流程预览已加载", "14:32:01 配方与图像样本已就绪", "14:32:02 测量结果使用示例数据"].map(t => <div key={t}><span className="wf-log-dot" />{t}</div>)}</div><button className="btn" onClick={() => notify("诊断检查完成，当前页面为本地操作流程预览。")}><Power size={15} />运行诊断检查</button></Panel>}
  </>;
}
