import type { TagPreset } from "../features/plc";

export const inspectionTagPresets: TagPreset[] = [
  { value: "partStart", label: "工件开始（PLC→PC）" },
  { value: "partEnd", label: "触发计划完成（PLC→PC）" },
  { value: "resultAck", label: "结果确认（PLC→PC）" },
  { value: "faultReset", label: "故障复位（PLC→PC）" },
  { value: "plcHeartbeat", label: "PLC 心跳（PLC→PC）" },
  { value: "protocolVersion", label: "协议版本（PLC→PC）" },
  { value: "requestSeq", label: "请求序号（PLC→PC）" },
  { value: "partSn", label: "工件序列号（PLC→PC）" },
  { value: "productCode", label: "产品代码（PLC→PC）" },
  { value: "shotCount", label: "计划拍照点数（PLC→PC）" },
  { value: "planVersion", label: "拍照计划版本（PLC→PC）" },
  { value: "planHash", label: "保留字段（PLC→PC）" },
  { value: "camera1Shots", label: "相机 1 计划点数（PLC→PC）" },
  { value: "camera2Shots", label: "相机 2 计划点数（PLC→PC）" },
  { value: "camera3Shots", label: "相机 3 计划点数（PLC→PC）" },
  { value: "camera1Triggers", label: "相机 1 触发数（PLC→PC）" },
  { value: "camera2Triggers", label: "相机 2 触发数（PLC→PC）" },
  { value: "camera3Triggers", label: "相机 3 触发数（PLC→PC）" },
  { value: "ackSeq", label: "确认序号（PLC→PC）" },
  { value: "visionReady", label: "视觉就绪（PC→PLC）" },
  { value: "armed", label: "已布防（PC→PLC）" },
  { value: "busy", label: "检测中（PC→PLC）" },
  { value: "done", label: "结果有效（PC→PLC）" },
  { value: "visionFault", label: "视觉故障（PC→PLC）" },
  { value: "pcHeartbeat", label: "上位机心跳（PC→PLC）" },
  { value: "pcProtocolVersion", label: "上位机协议版本（PC→PLC）" },
  { value: "acceptedSeq", label: "已接受请求序号（PC→PLC）" },
  { value: "acceptedPlanHash", label: "保留字段（PC→PLC）" },
  { value: "resultSeq", label: "结果序号（PC→PLC）" },
  { value: "resultCode", label: "结果码（PC→PLC）" },
  { value: "faultCode", label: "异常码（PC→PLC）" },
  { value: "resultSn", label: "结果 SN（PC→PLC）" },
];

export const inspectionHandshakeTags = new Set(inspectionTagPresets.map(preset => preset.value));
